import type { Metadata } from "next";
import { Fira_Mono } from "next/font/google";
import "./globals.css";

const fira_mono = Fira_Mono({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nikhil's Portfolio",
  description: "Generated by NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira_mono.className}>{children}</body>
    </html>
  );
}
